version: '3.8'

services:

  web:
    build: 
      context: ./frontend
      dockerfile: dockerfile
    ports:
      #- "50081:80"
      - "4200:4200"
    depends_on:
      - php
    networks:
      - frontend
      - backend
    volumes:
      - ./:/var/www

  php:
    tty: true
    container_name: laravel
    build: 
      context: ./backend
      dockerfile: dockerfile
    ports:
      - 8000:8000
    networks:
      - backend
    depends_on:
      - database

  database:
    container_name: mysql
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - "./mysql/projekt.sql:/docker-entrypoint-initdb.d/1.sql"
    networks:
      - backend


  phpMyAdmin:
    image: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - '8080:80'
    networks:
      - backend


networks:
  frontend:
  backend: